In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

<h3 align="center">$\mathbb{A}\vec{x} = \vec{v}$</h3> 


<h3 align="center">$
\begin{pmatrix}
2 & 1 & 4 & 1\\
3 & 4 & -1 & -1\\
1 & -4 & 1 & 5\\
2 & -2 & 1 & 3\\
\end{pmatrix}
  \begin{align}
    \begin{pmatrix}
           w \\
           x \\
           y \\
           z 
    \end{pmatrix}
    =
    \begin{pmatrix}
           -4 \\
           3 \\
           9 \\
           7 
         \end{pmatrix}
  \end{align}
$</h3> 

In [2]:

# Matriz que representa el sistema a resolver
A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)


v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver


In [3]:
v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver
N = len(v)   #dimension

A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)



# Eliminacion Gaussiana
for m in range(N):
    
    print(A)

    # Localizo el elemento a pivotear
    div = A[m,m]
    print(div)
    
#   A[m,:] = A[m,:]/div
    A[m,:] /= div  # divido el renglon que toca entre su pivote
    # Recuerda que A[m,:] = es el renglon m
    # Recuerda que a/=b divide por b y reasigna el resultado a la variable a, es lo mismo que a = a/b
    print("-----------------")
    print(A)
    
    v[m] /= div      # También dividimos al vector del sistema por el pivote
    print(v)
    print("-----------------")

print("********************************")    
print("********************************")    
print(A)


[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
2.0
-----------------
[[ 1.   0.5  2.   0.5]
 [ 3.   4.  -1.  -1. ]
 [ 1.  -4.   1.   5. ]
 [ 2.  -2.   1.   3. ]]
[-2.  3.  9.  7.]
-----------------
[[ 1.   0.5  2.   0.5]
 [ 3.   4.  -1.  -1. ]
 [ 1.  -4.   1.   5. ]
 [ 2.  -2.   1.   3. ]]
4.0
-----------------
[[ 1.    0.5   2.    0.5 ]
 [ 0.75  1.   -0.25 -0.25]
 [ 1.   -4.    1.    5.  ]
 [ 2.   -2.    1.    3.  ]]
[-2.    0.75  9.    7.  ]
-----------------
[[ 1.    0.5   2.    0.5 ]
 [ 0.75  1.   -0.25 -0.25]
 [ 1.   -4.    1.    5.  ]
 [ 2.   -2.    1.    3.  ]]
1.0
-----------------
[[ 1.    0.5   2.    0.5 ]
 [ 0.75  1.   -0.25 -0.25]
 [ 1.   -4.    1.    5.  ]
 [ 2.   -2.    1.    3.  ]]
[-2.    0.75  9.    7.  ]
-----------------
[[ 1.    0.5   2.    0.5 ]
 [ 0.75  1.   -0.25 -0.25]
 [ 1.   -4.    1.    5.  ]
 [ 2.   -2.    1.    3.  ]]
3.0
-----------------
[[ 1.          0.5         2.          0.5       ]
 [ 0.75        1.         -0.25       

In [4]:
v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver
N = len(v)   #dimension

A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)


# Eliminacion Gaussiana
for m in range(N):
    
    # Localizo el elemento a pivotear
    div = A[m,m]    
    A[m,:] /= div  # divido el renglon que toca entre su pivote    
    v[m] /= div      # También dividimos al vector del sistema por el pivote

############ Una vez "pivoteado" el renglon

    for i in range(m+1,N):
        mult = A[i,m]          #encontramos el elemento por el que debemos multiplicar
        A[i,:] = A[i,:] - mult*A[m,:]   # y multiplicamo el renglon por dicho numero y se lo restamos al renglón de abajo
        v[i] = v[i] - mult*v[m]        # hacemos las mismas operaciones para el vector de resultados     

    print(A)
    print("-----------------")
    print(v)
    print("********************************")   

        
print(A)
print("-----------------")
print(v)



[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
-----------------
[-2.  9. 11. 11.]
********************************
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.    0.  -11.4  -1. ]]
-----------------
[-2.   3.6 27.2 21.8]
********************************
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [ 0.   0.   0.  -1. ]]
-----------------
[-2.   3.6 -2.  -1. ]
********************************
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
-----------------
[-2.   3.6 -2.   1. ]
********************************
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
-----------------
[-2.   3.6 -2.   1. ]


## Eliminación Gussiana

In [5]:
v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver
N = len(v)   #dimension

A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)


# Eliminacion Gaussiana
for m in range(N):
    
    # Localizo el elemento a pivotear
    div = A[m,m]    
    A[m,:] /= div  # divido el renglon que toca entre su pivote    
    v[m] /= div      # También dividimos al vector del sistema por el pivote

    for i in range(m+1,N):
        mult = A[i,m]          #encontramos el elemento por el que debemos multiplicar
        A[i,:] = A[i,:] - mult*A[m,:]   # y multiplicamo el renglon por dicho numero y se lo restamos al renglón de abajo
        v[i] = v[i] - mult*v[m]        # hacemos las mismas operaciones para el vector de resultados     
        
        

############ Una vez "triangulizada" la matriz  realizamos el  Backsubstitution

x = np.empty(N,float)  #definimos unvector x vacio

for m in range(N-1,-1,-1):
    x[m] = v[m]               #asignamos a x el valor del ultimo elemento
    print(x)
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]
    print("-----------------")

    print(x)

        
print("********************************")    
print(A)  

[0. 0. 0. 1.]
-----------------
[0. 0. 0. 1.]
[ 0.  0. -2.  1.]
-----------------
[ 0.  0. -2.  1.]
[ 0.   3.6 -2.   1. ]
-----------------
[ 0. -1. -2.  1.]
[-2. -1. -2.  1.]
-----------------
[ 2. -1. -2.  1.]
********************************
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]


In [ ]:
A[2,:]

In [ ]:
v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver
N = len(v)   #dimension

A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)


# Eliminacion Gaussiana
for m in range(N):
    
    # Localizo el elemento a pivotear
    div = A[m,m]    
    A[m,:] /= div  # divido el renglon que toca entre su pivote    
    v[m] /= div      # También dividimos al vector del sistema por el pivote

############ Una vez "pivoteada" la matriz

    for i in range(m+1,N):
        mult = A[i,m]          #encontramos el elemento por el que debemos multiplicar
#         A[i,:] -= mult*A[m,:]
#         v[i] -= mult*v[m]
